# Generated by Django 5.2.3 on 2025-11-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0002_alter_task_due_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='slug',
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images'),
        ),
    ]
