# Generated by Django 5.2.3 on 2025-12-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistapp', '0005_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_time',
            field=models.TimeField(blank=True),
        ),
    ]
